<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit8ae613f723cb911e2e32817dd67ce219
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Castlegate\SchemaMap\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Castlegate\SchemaMap\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit8ae613f723cb911e2e32817dd67ce219', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Castlegate\SchemaMap\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit8ae613f723cb911e2e32817dd67ce219', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Castlegate\SchemaMap\Vendor\Composer\Autoload\ComposerStaticInit8ae613f723cb911e2e32817dd67ce219::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
